-- MySQL Script generated by MySQL Workbench
-- qua 26 nov 2025 09:37:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dcmen_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dcmen_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dcmen_bd` DEFAULT CHARACTER SET utf8 ;
USE `dcmen_bd` ;

-- -----------------------------------------------------
-- Table `dcmen_bd`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcmen_bd`.`tipo_usuario` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `modulo_adm` VARCHAR(1) NOT NULL,
  `modulo_vendas` VARCHAR(1) NOT NULL,
  `modulo_compras` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcmen_bd`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcmen_bd`.`usuarios` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(20) NULL,
  `senha` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `tipo_usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_tipo_usuario_idx` (`tipo_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tipo_usuario`
    FOREIGN KEY (`tipo_usuario_id`)
    REFERENCES `dcmen_bd`.`tipo_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcmen_bd`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcmen_bd`.`categorias` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcmen_bd`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcmen_bd`.`marcas` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcmen_bd`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcmen_bd`.`produtos` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `cor` VARCHAR(45) NOT NULL,
  `tamanho` VARCHAR(5) NOT NULL,
  `caminho_img` VARCHAR(200) NULL,
  `categoria_id` INT NOT NULL,
  `marca_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produto_categoria1_idx` (`categoria_id` ASC) VISIBLE,
  INDEX `fk_produto_marca1_idx` (`marca_id` ASC) VISIBLE,
  CONSTRAINT `fk_produto_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `dcmen_bd`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_marca1`
    FOREIGN KEY (`marca_id`)
    REFERENCES `dcmen_bd`.`marcas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `dcmen_bd`.`tipo_usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `dcmen_bd`;
INSERT INTO `dcmen_bd`.`tipo_usuario` (`id`, `nome`, `modulo_adm`, `modulo_vendas`, `modulo_compras`) VALUES (1914, 'ADMIN', 'S', 'S', 'S');

COMMIT;


-- -----------------------------------------------------
-- Data for table `dcmen_bd`.`usuarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `dcmen_bd`;
INSERT INTO `dcmen_bd`.`usuarios` (`id`, `nome`, `telefone`, `senha`, `email`, `tipo_usuario_id`) VALUES (1914, 'ADMIN', '', 'c2abf3fd0a86e343487ac58f45a8b82d6ac813bd6a6b4f80939181944d5f0ec', 'admin@admin.com', 1914);

COMMIT;

